server:
  servlet:
    port: 8080
    contextPath: /api

spring:

  application:
    name: trello_qoura

  datasource:
    url: jdbc:postgresql://localhost:5432/quora
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect